aws-amplify/amplify-ui-android

.editorconfig
authenticator/build.gradle
authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/auth/AmplifyAuthConfiguration.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/forms/FieldConfig.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/forms/FieldValidator.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/forms/FormBuilder.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/states/ScreenStateFactory.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/strings/StringResolver.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/PasswordReset.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/PasswordResetConfirm.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/PhoneInputField.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignIn.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignInConfirmCustom.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignInConfirmMfa.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignUp.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignUpConfirm.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/VerifyUser.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/VerifyUserConfirm.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthProvider.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthenticatorMessage.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/Errors.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/MissingConfigurationException.kt
authenticator/src/main/res/values/messages.xml
build.gradle

chore(authenticator): Authenticator KtLint check

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/DateInputField.kt
authenticator/src/main/res/drawable/ic_authenticator_calendar.xml
authenticator/src/main/res/values/fields.xml

N/A
- Add a material3 datepicker to date fields. User can type in the date directly in the field or click the calendar button to open the date picker.
Manual test

feat(authenticator): Add a material3 datepicker to date fields.

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/Authenticator.kt

n/a
- onDisplayMessage should not be a suspending function. Although a callback from a coroutine context, it is not idiomatic to have it be a suspending function since the invoking context is scoped to the Authenticator composable. Instead, consumer should launch a new coroutine in their desired scope.
n/a

fix(authenticator): Make onDisplayMessage not a suspending function

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthenticatorMessage.kt

- Rename `Information` to `Info` to match the Swift naming.

fix(authenticator): Rename AuthenticatorMessage.Information to AuthenticatorMessage.Info

---

liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt

*Description of changes:* Check for an empty session ID at the beginning of the liveness flow before starting the liveness challenge.
Tested in the liveness sample app.

fix(liveness): check for empty session ID

---

.github/workflows/ci-unit-tests.yml

Use GitHub var instead of secrets to store the role ARN. This will unblock PRs from external contributors.
N/A

chore: Use vars to store IAM role instead of secrets

---

.github/workflows/ci-unit-tests.yml

*Description of changes: Pin github actions by commit-hash instead of tags

chore: pin github actions by commit hash

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorMatchers.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/MockAuthenticatorData.kt
gradle/libs.versions.toml
testing/src/main/java/com/amplifyframework/ui/testing/CoroutineTestRule.kt

Authenticator will shown a generic error message and emit a useful error log if an unsupported next step is received.
Log Message:
UX:
- Tried to sign in with TOTP enabled

fix(Authenticator): Add error messages when a TOTP next step is received

---

liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/state/LivenessState.kt
liveness/src/main/res/values/strings.xml
samples/liveness/app/src/main/res/values/strings.xml

REQUIRES AMPLIFY VERSION BUMP AFTER [AMPLIFY PR](https://github.com/aws-amplify/amplify-android/pull/2577) IS RELEASED
Read facematch timeout from server -- should be attached to the event we get back from Amplify.  Also remove all wording of 7 second fixed timeout.

fix(liveness): Use server facematch timeout

---

build.gradle.kts

Add License validation step as part of `gradlew build` 

chore: Add build-time dependency license check

---

liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/ui/InstructionMessage.kt
samples/liveness/app/src/main/java/com/amplifyframework/ui/sample/liveness/MainViewModel.kt
samples/liveness/app/src/main/java/com/amplifyframework/ui/sample/liveness/ui/ResultScreen.kt

* Add spinner to "Connecting" prompt
* Improve results screen to show timeout message.

fix(liveness): Minor UI Fixes

---

README.md
liveness/CHANGELOG.md
liveness/gradle.properties
samples/liveness/build.gradle

chore: release liveness 1.2.0

---

README.md
liveness/CHANGELOG.md
liveness/gradle.properties
samples/liveness/build.gradle

*Description of changes:
Liveness 1.2.1

chore: Release liveness 1.2.1

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthProvider.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/Exceptions.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt

#105 
#98 
Log a more descriptive error if amplify configuration is incomplete or invalid.
Log messages now look like:
> InvalidConfigurationException{message=No value for verificationMechanisms, cause=org.json.JSONException: No value for verificationMechanisms, recoverySuggestion=Check that the configuration passed to Amplify.configure has all required fields}
- Removed/edited fields in my amplifyconfiguration.json, ran Authenticator

fix(authenticator): Improve error messaging if auth configuration is invalid/incomplete

---

build-logic/plugins/src/main/kotlin/ApiValidatorConventionPlugin.kt

- Elements marked `@VisibleForTesting` are not part of the public API

chore: Ignore VisibleForTesting-annotated elements for purposes of api validation

---

README.md
authenticator/CHANGELOG.md
authenticator/README.md
authenticator/gradle.properties
samples/authenticator/build.gradle

release: Authenticator 1.1.0

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/MockAuthenticatorData.kt

#128 
If user does not have any of the required verification attributes do not show the attribute verification screen (because there is nothing to verify)
Added various unit tests around showing the attribute verification screen.
Followed steps described in issue

fix(authenticator): Do not show empty user verification screen

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/Exceptions.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorMatchers.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt

*Issue #, if available:* #151
Instead of only checking direct `cause`, look through the chain of `cause` to see if an error's root cause was a network error.
- Verified expected connectivity message appears when trying to sign in with airplane mode.

fix(authenticator): Fix emission of NetworkErrorMessage

---

.github/workflows/issue_comment.yml

- Some comments don't trigger the webhook because they have characters that are invalid for xargs.

chore: Remove characters from comment bodies before calling xargs

---

gradle/libs.versions.toml

New version of Amplify properly parses the requirements in Gen1 configs.

fix(authenticator): Update Amplify to fix parsing of uppercase/lowercase password requirements

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt

https://github.com/aws-amplify/amplify-ui-android/issues/160
Update password reset to automatically sign in after password reset successfully completes.  This matches with current behavior in [Amplify Swift](https://github.com/aws-amplify/amplify-ui-swift-authenticator/blob/main/Sources/Authenticator/States/ConfirmResetPasswordState.swift#L60-L75)
* Manually tested on simulator to ensure that password reset automatically signs user in on completion.  
* Manually tested use case when a user signs in with a temporary password is prompted with password reset and workflow works as expected.  
* Added a unit test for the sign case of when password reset is required due to temporary password requiring reset. …

fix: automatically sign in after password reset succeeds

---

scripts/fastlane/Fastfile

This change is to enable the release PR workflow to pick up the commit for release, without the "authenticator" scope in the commit message name. We will revert this change in the script after the release.

chore: authenticator release to include all scopes (temporary)

---

.github/workflows/release_pr.yml

chore: add missing component env variable in release_pr Github action

---

liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/model/FaceLivenessDetectionException.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/model/LivenessCheckState.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/state/AttemptCounter.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/state/LivenessState.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt
liveness/src/test/java/com/amplifyframework/ui/liveness/state/LivenessStateTest.kt

N/A
This adds support for a no-light challenge to the Liveness UI component. 
Notable Changes:
- Starts the liveness session immediately
- This is required to start the web socket and retrieve information about what kind of liveness challenge to render
- When starting the session, pass in a list of challenges that the component supports instead of a singular string
- Passes in additional telemetry attributes
- Updated unit tests
- Tested with the list of challenges in this PR and validated that backend will respond with one of those challenges
- Tested with a list of just FaceMovement and validated CX
- Tested with a list of just FaceMovementAndLight 2.0.0 and validated CX
- Tested with a list of just …

feat(liveness): Add support for a no light freshness challenge 

---

liveness/src/main/java/com/amplifyframework/ui/liveness/ml/FaceDetector.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/state/LivenessState.kt
liveness/src/test/java/com/amplifyframework/ui/liveness/ml/FaceDetectorTest.kt

N/A
This is a follow up to https://github.com/aws-amplify/amplify-android/pull/2883 where that PR starts passing server-provided values to the client, this removes the hard coded values to use those server-provided values.
"Hardcoded" different values from the Amplify library to see them reflected on the Liveness UI Component

feat(liveness): Use backend-provided values for some FaceDectector values

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt

*Issue #, if available:* [https://github.com/aws-amplify/amplify-ui-android/issues/189](url)
instead of "manually" _moveTo_ SignIn state after signing out, we could listen to HubEvents: _AuthChannelEventName.SIGNED_OUT_, which was implemented in _start() method of AuthenticatorViewModel.kt_.
Instead of testing the resulting state (which should be SignIn), we just need to make sure that _signOut()_ is being called when _getCurrentUser_ errors with _SessionExpiredException_ during start

chore(auth): refractor handleSignedIn method in AuthenticatorViewModel

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt

Added missing test cases in _AuthenticatorViewModelTest.kt_ for when _AuthSignInStep_ is one of the following:
- _CONFIRM_SIGN_IN_WITH_SMS_MFA_CODE_
- _CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE_
- _CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_
- _CONFIRM_SIGN_UP_

chore(auth): Completed unit tests for AuthenticatorViewModel's signIn region

---

build-logic/plugins/build.gradle.kts
build-logic/plugins/src/main/kotlin/AndroidLibraryConventionPlugin.kt

Use Java 17 JVM when building the project.
- Ensure project builds in Android Studio Ladybug

chore(all): Fix building in Android Studio Ladybug

---

liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/camera/PreviewTextureView.kt

The change monitors the camera binding and throws an error if no camera frames are detected within 5 seconds of an attempted launch.

fix(liveness): Detect failed camera opening

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/MockAuthenticatorData.kt
gradle/libs.versions.toml
samples/authenticator/app/build.gradle
samples/authenticator/build.gradle

#203 
Upgrade Amplify to 2.27.0 to get fix for `getCurrentUser` failing while offline with expired access tokens.
- Reproduced bug

fix(authenticator): Upgrade Amplify dependency to 2.27.0

---

.editorconfig
authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthProvider.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/MockAuthenticatorData.kt

This change fixes an issue where Authenticator would show an error after signup (requiring an app restart) if `USER_AUTH` has been enabled for the user pool, even if there is no intention to use that flow for sign in.
This is because having `USER_AUTH` enabled allows cognito to return the next sign up step of `COMPLETE_AUTO_SIGN_IN` which Authenticator could not handle. This PR adds support for this result.
- Unit tests
- Test app

fix(authenticator): Add support for auto-sign-in

---

gradle/libs.versions.toml
samples/liveness/app/build.gradle
samples/liveness/build.gradle
samples/liveness/settings.gradle

*Description of changes:* 
I've only updated the Liveness app for this change. Will update the Authenticator sample app in a follow up PR.
- Use the Gradle version catalog 
- Migrated dependencies that were in the sample app into the catalog
- Enabled desugaring and updated the Kotlin compiler version
- Updated the kotlin android plugin version to match what Amplify uses (or else it won't build)
Launched the sample app and verified liveness still works with no regression

chore(samples): Update the liveness sample app to use the latest compose bom

---

README.md
liveness/CHANGELOG.md
liveness/gradle.properties
samples/liveness/build.gradle

Amplify UI Android Liveness 1.4.2
Note: I had to create this PR manually because the GH action was having issues. For some reason, the latest commit was tagged for the previous liveness release even though it wasn't released which I think is why the action script can't find any "new" commits. I followed the manual release doc and mimicked a proper release PR as closely as I could. I tagged this commit with the proper 1.4.2 release tag as well.

release: Amplify UI Android Liveness 1.4.2

---

samples/liveness/settings.gradle

Noticed the sample app could not run because of an introduced error

chore(liveness): Fix syntax error in liveness sample settings

---

liveness/src/main/java/com/amplifyframework/ui/liveness/camera/OpenGLRenderer.java

*Description of changes:* 
We've reports that some old devices were crashing due to this line throwing a Runtime/IllegalStateException. Instead of crashing, we will now silently handle the exception and let the rest of the flow fail back to the app flow. We can now expect the following behaviors:
If the exception happens at the first frame, it'll fail fast because there is existing logic that says "if the camera preview hasn't initialized for the first 5 seconds, throw a camera failed to open exception." Alternatively, if the exception happens after the camera has initialized, the liveness check will eventually time out with an exception thrown with the cause being "Stream idle timeoutExceeded." Both of which are reasonable messaging to the developer.
*How did …

fix(liveness): Prevent crashing if there's an exception thrown by the SurfaceTexture

---

authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt
authenticator/src/test/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModelTest.kt

*Issue #, if available:* #235
Authenticator now reacts to `SIGNED_IN` events it receives from Amplify. Historically it didn't do this because the idea was that you would only use Authenticator for Sign In, and not use Amplify APIs directly, but #235 rightly points out that you currently would use Amplify for social sign in via Cognito's web UI, which would leave Authenticator in an incorrect state.
In this PR Authenticator listens to events from Amplify for when the user signs in. If the event is not expected (i.e. Authenticator is not currently in the process of calling a sign in API) then it reacts to the sign in by going directly to the `SignedInState`.
By submitting this …

feat(authenticator): Handle SignedIn events from outside of Authenticator

---

liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/ml/FaceDetector.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/state/LivenessState.kt
liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt

*Description of changes:* This change adds support for configuring the back camera to the liveness challege that will work in conjunction with the no light challenge. As such, this change will be merged to the no light feature branch so that it will release at the same time as no light.
Documentation will be updated when the full feature is merged to main

feat(liveness): Add support for configuring the back camera for the no light challenge

---

liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt

*Description of changes:* After a callout from Tyler and some additional testing, found that having the challenge option as part of the remembered state for the Composable will break since when the view is rendered, the session ID is considered started and thus can't be reused which is what happens when the Composable gets torn down and restarted. Instead, will have to add a callout to the docs change that developers will need to create a new session ID if they wish to change the camera orientation "on the fly"
*How did you test these changes?* Tested by attemping to "swap" camera options at runtime at the start view as well as while the liveness check is happening. Before this fix, the Composable would restart and Rekognition would return an exception saying …

fix(liveness): Remove challenge options from the FaceLivenessDetector key

---

gradle/libs.versions.toml
liveness/build.gradle.kts

*Issue #, if available:* #161
Updates Liveness to work with 16kb page size
- Verified Liveness session can run on device with 16kb page size enabled.

fix(liveness): 16kb Page Support for Liveness

---

liveness/src/main/java/com/amplifyframework/ui/liveness/state/LivenessState.kt
liveness/src/test/java/com/amplifyframework/ui/liveness/state/LivenessStateTest.kt

The challenge was starting even before the face was a proper distance away. Before the no-light PR, `readyForOval` was not set until the initial face distance check had passed. This corrects the previous behavior of no starting the challenge until the face is the correct distance away.

fix(liveness): Prevent challenge from restarting
