aws-amplify/amplify-ui-android

- samples/liveness/app/build.gradle
*Description of changes:* Fix the syntax of the liveness dependency in the sample app.
Ran the sample app.
> fix(liveness): update liveness dependency in sample app

- authenticator/README.md
Add usage instructions for Authenticator to the README.
> chore(authenticator): Add usage instructions to the README

- samples/authenticator/app/src/main/java/com/amplifyframework/ui/sample/authenticator/ThemeSelector.kt
- samples/authenticator/app/src/main/java/com/amplifyframework/ui/sample/authenticator/theme/amplifytheme/Color.kt
- samples/authenticator/app/src/main/java/com/amplifyframework/ui/sample/authenticator/theme/amplifytheme/Theme.kt
The sample app theme wasn't pushed due to gitignore rules. Change the package name to circumvent.
> fix(authenticator): Fix missing theme files due to ignored package

- .github/workflows/ci-unit-tests.yml
- Add a workflow for triggering our CI tests in Codebuild
> chore: Add a workflow file for triggering codebuild

- authenticator/src/main/java/com/amplifyframework/ui/authenticator/forms/FieldKey.kt
- authenticator/src/main/java/com/amplifyframework/ui/authenticator/forms/FormBuilder.kt
- authenticator/src/main/java/com/amplifyframework/ui/authenticator/forms/FormState.kt
> chore: Add additional API documentation for the forms package.

- authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/PasswordReset.kt
- authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthProvider.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/PasswordResetTest.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/SignInTest.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/SignUpTest.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/robots/PasswordResetRobot.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/robots/ScreenLevelRobot.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/robots/SignInRobot.kt
- authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/robots/SignUpRobot.kt
- build.gradle.kts
- testing/src/main/java/com/amplifyframework/ui/testing/ComposeRobot.kt
> chore: Introduce robot pattern for compose unit tests

- .github/ISSUE_TEMPLATE/1.bug_report.yaml
- .github/ISSUE_TEMPLATE/2.feature_report.yaml
N/A
1. Remove Language and Async Model sections as this is not relevant for UI components, which require use of Kotlin.
2. Add Authenticator to the list of components.
N/A
> chore: Update issue and feature request issue templates

- README.md
- Add information about individual components with links to docs, samples, and information about important version compatibility.
> chore: Improve the README with component information and compatibility guidance

- gradle/libs.versions.toml
- N/A
- Upgrade to Amplify 2.8.4
> chore: Upgrade to latest Amplify version

- authenticator/CHANGELOG.md
> chore(authenticator): Fix changelog

- README.md
- authenticator/CHANGELOG.md
- authenticator/README.md
- authenticator/gradle.properties
- samples/authenticator/build.gradle
Authenticator 1.0.0-dev-preview.2
> release: Authenticator 1.0.0-dev-preview.2

- README.md
- authenticator/CHANGELOG.md
- authenticator/README.md
- authenticator/gradle.properties
- samples/authenticator/build.gradle
> release: Authenticator 1.0.0

- .github/workflows/notify_comments.yml
- .github/workflows/notify_release.yml
N/A
- Add workflows to notify the Amplify Slack channel when there is a new comment or a new release.
> chore: Add notification workflows

- gradle/libs.versions.toml
- samples/liveness/build.gradle
*Description of changes:* Update Amplify Android version to latest.
Ran authenticator and liveness sample apps.
> chore: Update Amplify Android version

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release: Amplify UI Android Liveness 1.0.1

- liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt
*Description of changes:* Center camera preview in Liveness.
> fix(liveness): center camera preview

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release: Liveness 1.0.2

- samples/liveness/app/build.gradle
*Description of changes:* Update the Material3 dependency in the Liveness sample app to match the version used in Amplify UI Android Liveness.
Tested in a sample app.
> chore(liveness): update material dependency in liveness sample app

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release: Liveness 1.0.3

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release: Liveness 1.1.0

- gradle/libs.versions.toml
> Amplify version bump to 2.11.1

- README.md
*Description of changes: Update Amplify min version for Liveness
> Update Amplify min version for Liveness

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release liveness 1.1.2

- liveness/gradle.properties
- liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
REQUIRES AMPLIFY VERSION BUMP AFTER [AMPLIFY PR](https://github.com/aws-amplify/amplify-android/pull/2572) IS RELEASED
> fix(liveness): Add version to liveness websocket user agent

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release liveness 1.1.3

- README.md
- authenticator/CHANGELOG.md
- authenticator/README.md
- authenticator/gradle.properties
- samples/authenticator/build.gradle
> release authenticator 1.0.1

- gradle/libs.versions.toml
- samples/liveness/build.gradle
> chore: Update Amplify to 2.14.3

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/app/build.gradle
- samples/liveness/build.gradle
> release liveness 1.1.4

- gradle/libs.versions.toml
- samples/liveness/build.gradle
> chore: Update to Amplify Android 2.14.5

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release liveness 1.1.5

- README.md
- authenticator/CHANGELOG.md
- authenticator/README.md
- authenticator/gradle.properties
- gradle/libs.versions.toml
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/authenticator/build.gradle
- samples/liveness/app/build.gradle
- samples/liveness/build.gradle
> chore: release liveness 1.1.6 and authenticator 1.0.2

- liveness/src/main/res/values/strings.xml
- samples/liveness/app/src/main/java/com/amplifyframework/ui/sample/liveness/ui/ResultScreen.kt
- samples/liveness/app/src/main/res/values/strings.xml
> fix(liveness): ui updates

- authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorState.kt
- Use coroutine scope tied to the composable instead of the viewmodel so that the authenticator state instance is not leaked on configuration change.
> fix(authenticator): Don't use viewModelScope from the state holder

- CONTRIBUTING.md
- authenticator/api/authenticator.api
- build-logic/plugins/build.gradle.kts
- build-logic/plugins/src/main/kotlin/ApiValidatorConventionPlugin.kt
- build-logic/plugins/src/main/kotlin/ComponentConventionPlugin.kt
- build.gradle.kts
- gradle/libs.versions.toml
- liveness/api/liveness.api
- Adding the binary compatibility validator plugin. This plugin validates that our public API matches the contents of a `.api` file that is stored in source control.
- Verified that public API changes will fail `check` task
> chore: Add Binary Compatibility Validator

- liveness/src/main/java/com/amplifyframework/ui/liveness/model/LivenessCheckState.kt
> fix(liveness): fix typo in state messages

- liveness/api/liveness.api
- liveness/build.gradle.kts
- liveness/src/main/java/com/amplifyframework/ui/liveness/camera/FrameAnalyzer.kt
- liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
- liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessMuxer.kt
- liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessVideoEncoder.kt
- liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt
* [Prevent edge case of multiple success/failure callbacks](https://github.com/aws-amplify/amplify-ui-android/commit/91002125da2fcba4df0ed4f88b02377c8c1c07d7)
* [Attempted fix which could result in wrong liveness version being passed.](https://github.com/aws-amplify/amplify-ui-android/commit/9c2cf6dd550c6a31ba4214a8d43cc2c8c4ed9e98)
* [Prevent crash if frame fails to analyze](https://github.com/aws-amplify/amplify-ui-android/commit/f942c6a3f1887461f6830da2f22699a2f41fd57b)
* [Prevent crash if liveness muxer fails to initialize](https://github.com/aws-amplify/amplify-ui-android/commit/794619337697439a33cf52870a33dc099ca8d8d0)
* [prevent crash if muxer fails to write encoded chunk](https://github.com/aws-amplify/amplify-ui-android/commit/2fa …
> fix(liveness): Multiple Liveness Bug Fixes

- gradle/libs.versions.toml
- samples/liveness/app/build.gradle
- samples/liveness/build.gradle
> fix(liveness): Update Amplify to 2.14.12 to fix InvalidSignatureException

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release: Liveness 1.2.3

- gradle/libs.versions.toml
- samples/liveness/build.gradle
> chore(liveness): bump Amplify 2.15.0

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
*Description of changes:
Liveness 1.2.5
> release: Liveness 1.2.5 Release

- liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
- liveness/src/main/java/com/amplifyframework/ui/liveness/ui/FaceLivenessDetector.kt
> fix(liveness): Catch unhandled exceptions in coordinator

- README.md
- liveness/CHANGELOG.md
- liveness/gradle.properties
- samples/liveness/build.gradle
> release: Liveness 1.2.6

- .github/CODEOWNERS
Admins have to approve PRs that include API changes.
> chore: Require admin approval for changes to .api files

- README.md
- authenticator/CHANGELOG.md
- authenticator/README.md
- authenticator/gradle.properties
- samples/authenticator/build.gradle
> release: Authenticator 1.2.1 Release

- scripts/Gemfile
- scripts/Gemfile.lock
Add `rexml` to the Gemfile, and ran `bundle update`
> chore: update rexml to 3.3.2

- scripts/fastlane/Fastfile
* Minor update to release `product_name` and `release_title` config values that gets include in release PRs
* Update `changelog_include_scopes` config values for Authenticator component that was temporarily removed in order to get the first automated release PR to work (https://github.com/aws-amplify/amplify-ui-android/pull/169)
> chore: cleanup fastlane release configuration

- .github/workflows/issue_closed.yml
- .github/workflows/issue_comment.yml
- .github/workflows/issue_labeled.yml
- .github/workflows/issue_opened.yml
Renames "pending-response" to "pending-community-response"
Adds "pending-maintainer-response" when new community issue opened
Removes "pending-maintainer-response" when owner/maintainer comments on issue
Adds "pending-maintainer-response" when community comments on issue
removes "pending-maintainer-response" when issue is closed
No longer considers "improvement" as reason to remove "pending-triage-label"
> chore: Update action labels

- .github/workflows/issue_closed.yml
> chore: Update issue_closed.yml

- gradle/libs.versions.toml
> chore(all): Upgrade Amplify dependency

- gradle/libs.versions.toml
*Description of changes:* This just bumps the dependency specifically to pull in https://github.com/aws-amplify/amplify-android/pull/2923
Build succeeded
> chore(liveness): Update Amplify dependency to 2.23.0

- gradle/libs.versions.toml
*Description of changes:* Updates the Amplify dependency to the latest version
Test ran both the Authenticator and Liveness sample apps. Both function properly with no regression.
> chore(all): Update Amplify dependency to 2.27.2

- .github/workflows/codecov_code_coverage.yml
- codecov.yml
Adds a GitHub workflow for uploading kover reports to codecov
> chore: Add codecov upload workflow

- .github/ISSUE_TEMPLATE/1.bug_report.yaml
- .github/ISSUE_TEMPLATE/2.feature_report.yaml
- README.md
Minor updates to github templates
n/a
> chore: Update GitHub templates
